### ISSUE TITLE
Occasionaly missing Interactive metrics

### ISSUE THREAD

**Issue by omares** [catchpoint/WebPageTest#1276]
Hey,

some of our WebPagetest runs that are trigged via the API are missing the Interactive metrics like `FirstInteractive` (e.g. a run from [29/05/2019, 05:03:37](https://www.webpagetest.org/result/190529_DY_2c4aa6ea7c728b5930f99e02a2f47a97/?f=json&average=0&median=0&standard=0&requests=0&console=0)).

Unfortunately i am out of ideas on how to debunk the problem and would be really grateful on any tips. 

Is there maybe a setting that we could apply to increase the wait time?

Thanks!

**Comment by wildlyinaccurate** [comment]
Hopefully this comment isn't too late to help someone: if FirstInteractive and ConsistentlyInteractive are missing, it might be because there was not a 5 second period during the page load that had no long tasks. You can use `setActivityTimeout 5000` to ensure there is always a 5 second gap at the end of the test. This increases the likelihood of FI/CI being measured. Failing that, you can probably fall back to LastInteractive.
