### ISSUE TITLE
EC2 AMI: Server vs Agent

### ISSUE THREAD

**Issue by gaurav5430** [catchpoint/WebPageTest#1322]
Trying to setup a private instance of webpagetest.

It is mentioned that the Server AMI can automatically instantiate and terminate agents on EC2.

> There is an EC2 AMI available for the WebPageTest server that provides a lot of benefits:
> 
> No configuration required (up and running in 5 minutes).
> Automatically starts and stops EC2 test agents in all of the EC2 regions as needed.
> Automatically updates to the latest server and agent code.

On [this page](https://github.com/WPO-Foundation/webpagetest-docs/blob/master/user/Private%20Instances/ec2_agents.md) though, there is a list of agent AMIs.
Does it mean that there is a way to disable the auto instantiation behavior and setup an agent EC2  separately?

What benefits would it have?
Is there a separate server AMI for this use case, or the same AMI has some configuration options to not let it control the agent instantiation and termination ?

**Comment by gaurav5430** [comment]
In [settings.ini sample](https://github.com/WPO-Foundation/webpagetest/blob/master/www/settings/settings.ini.sample):

```
; Use if the server will be auto-starting/stopping EC2 test agents
;ec2_key=<access key>
;ec2_secret=<secret>
```

Would not providing these automatically opt us out of the automatic instantiation and termination, or is there another flag that handles that?

**Comment by pmeenan** [comment]
Yes, removing the keys (or never setting them) from settings.ini would disable the auto start/stop.

I don't use the auto start/stop myself for example.  I just have a static pool of persistent spot requests in each of the regions with the number of agents I need.

On GCE for a bulk testing system I would use CPU-based auto-scaling to have it scale up to thousands of agents if needed when the per-agent CPU average was higher than 15% (i.e. they were active).  That worked for that specific case because I had a weekly batch of a few million pages to test so the system would scale up when it started and automatically scale back down when done.

**Comment by gaurav5430** [comment]
Thanks, that was a lot helpful.

As i understand, you are not using the auto start/stop so that you can have more control over the agents' instantiation and lifecycle.

Is there some documentation on how to setup agents separately?

**Comment by pmeenan** [comment]
There's no specific documentation for the agents outside of the [user data string](https://github.com/WPO-Foundation/webpagetest-docs/blob/master/user/Private%20Instances/ec2_agents.md#example-user-data-string) info on the docs page.

You basically check locations.ini for the location ID for each of the regions where you want to run agents and then just start instances using the appropriate AMI for that region (c5 persistent spot instances work great).  In the config for the agent you just need to specify the user data string telling it the server name (or IP address), location ID and location key (if you are using one) and it will automatically start connecting to the server when it starts.
