### ISSUE TITLE
Running multiple instances of server

### ISSUE THREAD

**Issue by bramevo** [catchpoint/WebPageTest#1332]
I was trying to figure out how to run multiple instances of server. For agents it's easy to run multiple of them as the servers are handling those, but would it be possible to run multiple instances of server? To get an high available service out of it.

Seems that there is no database running on the server instance, so I would think all data is kept in following folders:
/var/www/webpagetest/www/results
/var/www/webpagetest/www/tmp

So what if I would create docker container that mounts an NFS and create links for the above directories on the NFS storage.
Would I be missing anything else? Or is there a risk that multiple instances might be locking files that the other might need?

**Comment by pmeenan** [comment]
The servers are mostly stateless and there are a few things it has available to make it possible to scale but how you put them together depends heavily on what you're trying to do.

The "stateful" directories are results, tmp and work/jobs.  If you just want multiple containers to look like one server then NFS mounting those somewhere should do it as long as the mount supports flock operations (the tmp directory is filled with lock files to prevent concurrent writing to the same result, work queue or test ID generation).

The server supports a "[serverID](https://github.com/WPO-Foundation/webpagetest/blob/master/www/settings/settings.ini.sample#L152)" setting in settings.ini that will namespace all of the test ID's based on the server ID so you can avoid collisions in the results just by giving each server a unique server ID.  Then you don't have to worry about multiple servers locking the tests.

The server supports "archiving" tests to a path or a S3-API storage server and every server will check the archive if a test isn't available locally when viewing a result. Any server can display any test from the archive independent of the server ID so you can just use a shared archive instead of mounting the results folder or you can have separate servers for presenting the results vs running the tests.

As far as work queues go, by default the server will use a filesystem-based work queue with files in the work/jobs directory.  If you want all agents to be able to run tests from all of the servers then you either need to use a shared work directory or use a beanstalk-based work queue.  The server has support for configuring a [beanstalk server](https://github.com/WPO-Foundation/webpagetest/blob/master/www/settings/settings.ini.sample#L131) to use for the work queue.  Usually I only use it for scaling a single server to handle huge test volumes with a localhost beanstalk server but you could also use an external queue.

You could also just have each server maintain it's own queue and have the agents only pull work from the given server in which case you don't have to worry about locking the work queue.

Currently the agent only supports talking to a single "server" (could be multiple behind the scenes if it is transparent).  It wouldn't be hard to add support to the agents to have them round-robin multiple servers.

At the end of the day, most people find the added complexity (which introduces availability problems of its own) isn't worth it and a single server is easier to deal with and available enough (the public server that gets attacked regularly and runs in my house generally runs with 3-4 9's of availability).

**Comment by bramevo** [comment]
I did activate NFSv4 using Amazon EFS yesterday and I noticed the following folders that might need to be stored on NFS:
logs/ -> keeps a logfile per day so if this file is saved on NFS (and updated by all server instances), the test history page will always show the complete list
results/ -> keeps the testing results. I did activate S3 with archive_days set to 0, because the idea is that I want to have them moved towards S3 asap. Might cause issues though if 2 servers try to move them to S3 at the same time
tmp/ -> noticed some json.gz files and queue.gz file together with a wpt_cron.dat file with as content a timestamp. I would guess that you don't want to share these? Currently do not see any reasons to put them on NFS yet, especially since it's a tmp folder.
work/jobs/ -> noticed folders for all locations which are empty (even after a test) and a uniqueId.dat file which has json content: {"day":39,"num":1} , so I guess this one can be kept local too.
Another approach could be to use sticky sessions on the loadbalancer to avoid that I have to put all the small things on the NFS storage too. But it would allow me to have 2 servers available. So I could run them on a cluster based of AWS Spot instances (cheaper nodes).
I'm using AWS ECS -> Docker for this setup.

I figured that if workers are looking for work, they will most likely fetch them from both servers in a round robin way so no issue there. Maybe there might be issues when it wants to ping back or update the server that the results are done, but I assume this is stateless as well? Or might this require the tmp/ folder to be shared on NFS?

serverID I figured that I could just use the first 4 characters of the dockerId for this. Currently I havent found any evidence of this changing the name or location of the results yet.

Regarding the beanstalk queue. I was currently thinking about using AWS SQS for queueing all tests, sending them to the servers and if no test results would be found after some time, I could just add them again. So it's not a big issue to have one high available queue in the service itself as long as I can resolve issues in a layer above by just rerunning a failed test.
