### ISSUE TITLE
Unable to start the run in WPT as none of the test agents are getting activated.

### ISSUE THREAD

**Issue by kavitakmr28** [catchpoint/WebPageTest#1620]
## Description
Unable to start the run in WPT as none of the test agents are getting activated.

Describe the issue you're seeing.

We are doing a WPT execution on our private instance. After starting the test none of the loactions's agent is getting activated. We have found out that the image (AMI) used to launch the WPT client has been removed. Now we want to update the new AMI IDs in the WPT configuration which might resolve the issue. But we are not aware that how can we get the latest AMI images from WPT and where to update it.

### Steps to reproduce
Running a test on private instance.
After starting the test, all the test are getting stuck in queue.
Test location's agent is not activating.

### Expected result
All location should get activate.

### Actual result
None of the test location's agents are getting activated.

### Related issues?
No

**Comment by kavitakmr28** [comment]
Hi Jeff, 
Could you please help us to resolve this issue?

Thanks,

**Comment by rposbo** [comment]
Since the EC2 agent AMIs no longer exist, you'll need to create your own. You can create a new EC2 instance and run the WPT agent installation script, then save that as an AMI and copy the ami to the regions you want it. Update the ami ID in your `locations.ini` and it will start kicking off tests for the new AMIs.

I've got a write up about this coming up ;)

**Comment by rposbo** [comment]
Here's that write up I mentioned @kavitakmr28 : 
https://www.robinosborne.co.uk/2021/11/24/webpagetest-private-instance-2021-edition/ 😃
