### ISSUE TITLE
Add command to clear cache

### ISSUE THREAD

**Issue by rviscomi** [catchpoint/WebPageTest#186]
In the "flow view" script, one page is navigated before logData is enabled. Most times, the intention is to prewarm the cache with the contents of the first navigation. In a minority of cases, though, the first navigation behaves more like a preconfiguration step, like setting a cookie. This is just an example, there's already a command to set cookies.

It would be awesome if there was a "clearCache" command or similar that would result in the next navigation having a "first view"-like experience.

Expected use case would be something like:

```
logData 0
navigate http://www.example.com/setCookie/
clearCache
logData 1
navigate http://www.example.com/
```

The most similar command is `expireCache`, which takes a seconds param. In effect, this suggested command would be like passing Infinity to expireCache.

**Comment by joaocunha** [comment]
:+1:

Is this on the roadmap?

**Comment by avandonkelaar** [comment]
Is this added. Since the cookie step is not working, this could be really useful.

**Comment by paulcalvano** [comment]
I've been experimenting with using the Chrome command line option `--disk-cache-size=1 ` to test service workers.    Since the service worker becomes active on the 3rd page, I have been using a combination of that command line param with a script that looks like this:

```
logData 0
navigate https://www.test.com/testpage
navigate https://www.test.com/testpage
logData 1
navigate https://www.test.com/testpage
```

This effectively bypasses cache while keeping the cookies in tact, which seems to be what you are looking for.    Hope that helps you with your tests!

For the Service Worker testing though, sometimes I want to test that 3rd page request with cleared cookies - so I'm definitely interested in the undocumented appraoch that @pmeenan mentioned above.   Can you share some details?

**Comment by avandonkelaar** [comment]
@paulcalvano are you aware of any command which might does the same for killing the open connections?

**Comment by paulcalvano** [comment]
Hi @avandonkelaar.   No, I'm not aware of any command of the sort.   You can see all the Chrome command switches [here ](https://peter.sh/experiments/chromium-command-line-switches/)if you are interested, but I do not see any way to either influence either the connection state or the timeout.

**Comment by avandonkelaar** [comment]
Hi @paulcalvano thnx for pointing me to that page. Will keep en eye on it.

**Comment by gilbertococchi** [comment]
Hi all, do you know if perhaps there is a command to clear the DNS resolution cache as well?

**Comment by rishi-raj-jain** [comment]
> There is an existing (undocumented) clearCache command but it wipes out cookies too so I don't think that helps much. Might not be too hard to just add a variant of it that only clears the file cache.

Is it usable right now? Definitely fits for my case.
