### ISSUE TITLE
Don't list hidden images in "Images within the initial viewport are being lazy-loaded" opportunity

### ISSUE THREAD

**Issue by nhoizey** [catchpoint/WebPageTest#2484]
## Feature Request Summary

In the "Images within the initial viewport are being lazy-loaded" opportunity, even hidden images are currently listed, while it's perfectly fine — and even preferable IMHO — if they load a little later.

### What's the motivation or use case for the change/feature?

It is frustrating to get a "Not bad" instead of a "Looks great!" for the "Is it quick?" category… 😅

I think lazy loading hidden images even if they are in the initial viewport can be a good idea.

A live example: https://www.webpagetest.org/result/221017_BiDcY8_EBF/2/experiments/#Quick

**Comment by scottjehl** [comment]
I like this idea and want to improve these metrics. 

I mocked up the following two custom metrics using int observer to collect visible/invisible images more appropriately. It seems to do what we want in the browser, but it's not yet working as a custom metric for some reason.

The hack timeout is there to try and give the observer a sec to run its collection, since it's all async and apparently opaque.

Would love ideas if anyone has them.

https://github.com/WPO-Foundation/webpagetest/blob/2484/www/settings/custom_metrics/imgs-out-viewport.js
and 
https://github.com/WPO-Foundation/webpagetest/blob/2484/www/settings/custom_metrics/imgs-in-viewport.js
