### ISSUE TITLE
Discrepancy between Firefox and Chrome initiation of the initial page load.

### ISSUE THREAD

**Issue by mjkozicki** [catchpoint/WebPageTest#3031]
## Description
When running tests from Firefox using various connection types such as Native, 4G, or Cable. Unlike Chrome, there is a significant delay in the initiation of the initial page load. The page discovery process starts after a few seconds when using Firefox.

### Steps to reproduce
Note that native connection is relatively better than other connection types as there is no traffic shaping involved. 
Target Firefox to start a test on different configuration for the connection. 
Target Chrome with the same configurations.
Note differences in waterfalls.

### Expected result
Explanation of Firefox and Chrome discrepancy and/or fix of the issue.

### Actual result
Tests executed via the Chrome browser exhibit the expected behavior, with page discovery initiating promptly at 0 seconds.
Test executed in Firefox have the discovery process starts after a few seconds when using Firefox.

Firefox 4g : https://www.webpagetest.org/result/231218_AiDcPN_3RC/1/details/#waterfall_view_step1
Firefox Cable: https://www.webpagetest.org/result/231221_BiDc5D_87H/1/details/#waterfall_view_step1
Firefox Native: https://www.webpagetest.org/result/231221_AiDcKD_8CH/1/details/#waterfall_view_step1
 
Chrome Run: https://www.webpagetest.org/result/231221_AiDcMN_8BG/1/details/#waterfall_view_step1

**Comment by pmeenan** [comment]
Looks like it is likely an issue with the processing of the mozilla logs for the connection setup timings (not, just DNS time at the beginning of each connection with no socket connect or TLS time).

The logs processing is fairly fragile since it literally parses log message output from Firefox to generate events and it is likely that some of the log messages changed.

Someone will have to grab the logs from an agent and update the [parser](https://github.com/catchpoint/WebPageTest.agent/blob/master/internal/support/firefox_log_parser.py).

**Comment by lbartoli79** [comment]
Resolved by https://github.com/catchpoint/WebPageTest.agent/pull/667
