### ISSUE TITLE
WPT does not support right click and dbClick which triggers trusted events.

### ISSUE THREAD

**Issue by MaryamHuntsperger** [catchpoint/WebPageTest#3049]
## Description
WPT scripting APIs do not include rightClick and dbClick events.

### Actual result
WPT should support rightClick and dbClick APIs which trigger trusted events.

### Related issues?
Any related issues filed already?
https://github.com/catchpoint/WebPageTest/issues/3048

**Comment by jspurlin** [comment]
FYI @slightlyoff. We currently have `click`/`clickAndWait` but there's no way to specify which button you are wanting to execute that click for. I think the easiest way would be to extend the parameter for `click`/`clickAndWait` to include a `button`, otherwise it'd probably be creating new WPT script actions for them (Although #3048 may push us to the "adding a param" approach if `click`/`clickAndWait` are the only WPT actions that are going to become trusted)

**Comment by mjkozicki** [comment]
This is an agent enhancement, referenced above.
