### ISSUE TITLE
WPT Not have test Brower Safari?

### ISSUE THREAD

**Issue by jirawat050** [catchpoint/WebPageTest#971]
![screen shot 2017-10-29 at 11 20 37 pm](https://user-images.githubusercontent.com/26427892/32146143-bee878de-bd05-11e7-854f-baa7cbca122d.png)

**Comment by pmeenan** [comment]
There is no Safari desktop agent but if you select one of the iPhones it will test mobile safari (which is where the vast majority of Safari usage is).

**Comment by jirawat050** [comment]
OKAY.but if macbook?

**Comment by pmeenan** [comment]
"There is no Safari desktop agent"

**Comment by jirawat050** [comment]
Thank you

**Comment by teerapat1739** [comment]
safari not support because hardly to develop on mac os

**Comment by ozcoder** [comment]
Desktop Safari has been getting better over the years and has had a big release recently. 
Is it still too hard to automate for WebPageTest?

**Comment by pmeenan** [comment]
@ozcoder it's not that Safari desktop is hard to automate (it supports webdriver out-of-the-box), it's a combination of things:

* Getting good instrumented data out of Safari for the requests (waterfall) is extremely difficult. The dev tools protocol that iOS supports remotely is not exposed on Desktop in a way that 3rd-party tooling can access it. That leaves in-page resource timing as the only way to get the request timings and it doesn't include headers (or even all of the requests). Visual metrics would work but the effort tradeoff isn't worth it.
* The VAST majority of Safari usage is on iOS devices (iPad and iPhone) and that already has good support in WebPageTest, including request-level details from the inspector protocol.
* Managing physical devices is an order of magnitude more expensive and difficult than VM's and Safari can't legally run in a VM on anything other than Mac hardware. This is more of an at-scale issue than basic support since WPT runs a few MacOS devices for doing iOS testing.
